defaults:
  - gru: default

_target_: lumos.world_models.contextrssm.lstm_cell.ContextLSTMCell
_recursive_: false

embed_dim: ???
action_dim: ${datamodule.action_space}

deter_dim: 256
stoch_dim: 32
stoch_rank: 32
context_dim: 16
hidden_dim: 256
layer_norm: true
ablate_context: false  # Set to true to disable context (ablation study)
