_target_: lumos.world_models.encoders.cnn_encoder.CnnEncoder
cnn_depth: 48
kernels: [4, 4, 4, 4]
strides: [2, 2, 2, 2]
paddings: [0, 0, 0, 0]
activation: elu
use_gripper_camera: ${world_model.use_gripper_camera}