accelerator: gpu
devices: 1
num_nodes: 1
precision: 32
max_epochs: 15
max_steps: -1
log_every_n_steps: 50
deterministic: false
num_sanity_val_steps: 0
limit_val_batches: 1.0
check_val_every_n_epoch: 1
