defaults:
  - datasets: vision_wm_debug
  - transforms: wm_basic
  - proprioception_dims: robot_full
  - observation_space: rgb_static_gripper_rel_act
  - batch_sampler: equidistant

_target_: lumos.datasets.calvin_data_module.CalvinDataModule
_recursive_: false
root_data_dir: ${root}/dataset/task_D_D
action_space: 7
action_max: [1., 1., 1., 1., 1., 1., 1.,]
action_min: [-1., -1., -1., -1., -1., -1., -1]
shuffle_val: false
load_feats: false

reset_prob: 0.01
batch_size: 64
seq_len: 10
