defaults:
  - encoder: cnn_encoder
  - decoder: cnn_decoder
  - lstm: contextlstm
  - amp: default
  - optimizer: adamw
  - loss: contextrssm

_target_: lumos.world_models.dreamer_v2_lstm.DreamerV2LSTM
_recursive_: false

name: dreamer_v2_lstm
train_batch_size: 16
val_batch_size: 16
robot_dim: 15
with_proprio: true
use_gripper_camera: true
