_target_: pytorch_lightning.loggers.WandbLogger
_recursive_: false
save_dir: ${log_dir}/wandb
save_code: true
name: null  # Will be set by setup_logger
group: null
log_model: false
project: ${script}
entity: null  # Uses your default wandb entity
id: null  # Will be set by setup_logger
offline: false  # Ensure online syncing to wandb